require 'rails_helper'

RSpec.describe 'invoices show page' do
  it 'displays a list of all the invoices and their attributes' do
    merchant_1 = Merchant.create!(name: "Schroeder-Jerde", created_at: Time.now, updated_at: Time.now)
    item_1 = Item.create!(name: "Watch", description: "Always a need to tell time", unit_price: 3000, merchant_id: merchant_1.id, created_at: Time.now, updated_at: Time.now)
    item_2 = Item.create!(name: "Crocs", description: "Worst and Best Shoes", unit_price: 4000, merchant_id: merchant_1.id, created_at: Time.now, updated_at: Time.now)
    item_3 = Item.create!(name: "Beanie", description: "Perfect for a cold day", unit_price: 5000, merchant_id: merchant_1.id, created_at: Time.now, updated_at: Time.now)
    item_4 = Item.create!(name: "Socks", description: "Everyone loves socks", unit_price: 6000, merchant_id: merchant_1.id, created_at: Time.now, updated_at: Time.now)
    item_5 = Item.create!(name: "Necklace", description: "Who even wears these anymore", unit_price: 7000, merchant_id: merchant_1.id, created_at: Time.now, updated_at: Time.now)
    item_6 = Item.create!(name: "Wallet", description: "Money pocket for your pocket", unit_price: 8000, merchant_id: merchant_1.id, created_at: Time.now, updated_at: Time.now)
    customer_1 = Customer.create!(first_name: "James", last_name: "Franco", created_at: Time.now, updated_at: Time.now)
    customer_2 = Customer.create!(first_name: "Frank", last_name: "Jameson", created_at: Time.now, updated_at: Time.now)
    customer_3 = Customer.create!(first_name: "John", last_name: "Smith", created_at: Time.now, updated_at: Time.now)
    customer_4 = Customer.create!(first_name: "Zack", last_name: "Adams", created_at: Time.now, updated_at: Time.now)
    customer_5 = Customer.create!(first_name: "Chloe", last_name: "Wheeler", created_at: Time.now, updated_at: Time.now)
    customer_6 = Customer.create!(first_name: "Zoe", last_name: "Atkins", created_at: Time.now, updated_at: Time.now)
    customer_7 = Customer.create!(first_name: "Mike", last_name: "Dao", created_at: Time.now, updated_at: Time.now)
    invoice_1 = customer_1.invoices.create!(status: 1, created_at: Time.now, updated_at: Time.now)
    invoice_2 = customer_1.invoices.create!(status: 1, created_at: Time.now, updated_at: Time.now)
    invoice_3 = customer_1.invoices.create!(status: 1, created_at: Time.now, updated_at: Time.now)
    invoice_4 = customer_2.invoices.create!(status: 1, created_at: Time.now, updated_at: Time.now)
    invoice_5 = customer_2.invoices.create!(status: 1, created_at: Time.now, updated_at: Time.now)
    invoice_6 = customer_2.invoices.create!(status: 0, created_at: Time.now, updated_at: Time.now)
    invoice_7 = customer_3.invoices.create!(status: 1, created_at: Time.now, updated_at: Time.now)
    invoice_8 = customer_3.invoices.create!(status: 1, created_at: Time.now, updated_at: Time.now)
    invoice_9 = customer_4.invoices.create!(status: 1, created_at: Time.now, updated_at: Time.now)
    invoice_10 = customer_4.invoices.create!(status: 1, created_at: Time.now, updated_at: Time.now)
    invoice_11 = customer_5.invoices.create!(status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_12 = customer_5.invoices.create!(status: 1, created_at: Time.now, updated_at: Time.now)
    invoice_13 = customer_6.invoices.create!(status: 1, created_at: Time.now, updated_at: Time.now)
    invoice_14 = customer_7.invoices.create!(status: 0, created_at: Time.now, updated_at: Time.now)
    invoice_15 = customer_7.invoices.create!(status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_1 = InvoiceItem.create!(item_id: item_1.id, invoice_id: invoice_1.id, quantity: 1, unit_price: item_1.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_2 = InvoiceItem.create!(item_id: item_1.id, invoice_id: invoice_2.id, quantity: 1, unit_price: item_1.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_3 = InvoiceItem.create!(item_id: item_1.id, invoice_id: invoice_3.id, quantity: 1, unit_price: item_1.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_4 = InvoiceItem.create!(item_id: item_1.id, invoice_id: invoice_4.id, quantity: 1, unit_price: item_1.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_5 = InvoiceItem.create!(item_id: item_1.id, invoice_id: invoice_5.id, quantity: 1, unit_price: item_1.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_6 = InvoiceItem.create!(item_id: item_1.id, invoice_id: invoice_6.id, quantity: 1, unit_price: item_1.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_7 = InvoiceItem.create!(item_id: item_1.id, invoice_id: invoice_7.id, quantity: 1, unit_price:item_1.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_8 = InvoiceItem.create!(item_id: item_1.id, invoice_id: invoice_8.id, quantity: 1, unit_price:item_1.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_9 = InvoiceItem.create!(item_id: item_1.id, invoice_id: invoice_9.id, quantity: 1, unit_price:item_1.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_10 = InvoiceItem.create!(item_id: item_1.id, invoice_id: invoice_10.id, quantity: 1, unit_price:item_1.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_11 = InvoiceItem.create!(item_id: item_1.id, invoice_id: invoice_11.id, quantity: 1, unit_price:item_1.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_12 = InvoiceItem.create!(item_id: item_1.id, invoice_id: invoice_12.id, quantity: 1, unit_price:item_1.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_13 = InvoiceItem.create!(item_id: item_1.id, invoice_id: invoice_13.id, quantity: 1, unit_price:item_1.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_14 = InvoiceItem.create!(item_id: item_4.id, invoice_id: invoice_14.id, quantity: 500, unit_price:item_4.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_15 = InvoiceItem.create!(item_id: item_6.id, invoice_id: invoice_14.id, quantity: 1, unit_price:item_4.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_16 = InvoiceItem.create!(item_id: item_1.id, invoice_id: invoice_14.id, quantity: 30, unit_price:item_1.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_17 = InvoiceItem.create!(item_id: item_2.id, invoice_id: invoice_14.id, quantity: 30, unit_price:item_2.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_18 = InvoiceItem.create!(item_id: item_3.id, invoice_id: invoice_14.id, quantity: 30, unit_price:item_3.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)
    invoice_item_19 = InvoiceItem.create!(item_id: item_5.id, invoice_id: invoice_15.id, quantity: 700, unit_price: item_5.unit_price, status: 2, created_at: Time.now, updated_at: Time.now)

    # visit_merchant_invoice_path(merchant_1, invoice_1)
    visit "/merchants/#{merchant_1.id}/invoices/#{invoice_1.id}"

    expect(page).to have_content(invoice_1.id)
    expect(page).to have_content(invoice_1.status)
    expect(page).to have_content(invoice_1.created_at.strftime("%-m/%d/%y"))
    expect(page).to have_content(invoice_1.name)
  end
end
