require 'rails_helper'

RSpec.describe Invoice, type: :model do
  describe 'validations' do
    it { should validate_presence_of(:status) }
  end

  describe 'relationships' do
    it { should belong_to(:customer) }
    it { should have_many(:invoice_items) }
    it { should have_many(:transactions) }
    it { should have_many(:items).through(:invoice_items) }
    it { should have_many(:merchants).through(:items) }
  end

  it 'can calculate total revenue generated by an invoice' do
    @merchant_1 = Merchant.create!(name: "Bread Pitt")
    @customer_1 = Customer.create!(first_name: "Meat", last_name: "Loaf")

    @invoice_4 = Invoice.create!(status: 2, customer_id: @customer_1.id)
    @item_4 = Item.create!(name: "Bread Roll", description: "Round, soft", unit_price: 850, merchant_id: @merchant_1.id)
    @invoice_item_4 = InvoiceItem.create!(quantity: 4, unit_price: 960, status: 2, item_id: @item_4.id, invoice_id: @invoice_4.id)

    expect(@invoice_4.total_revenue).to eq(3840)
  end

end
