require 'rails_helper'

RSpec.describe Merchant, type: :model do
  describe 'relationships' do
    it { should have_many(:items) }
  end

  describe 'instance methods' do
    before(:each) do
      @merch_1 = create(:merchant)
      @cust_1 = create(:customer)
      @cust_2 = create(:customer)
      @cust_3 = create(:customer)
      @cust_4 = create(:customer)
      @cust_5 = create(:customer)
      @cust_6 = create(:customer)
      @item_1 = create(:item, merchant: @merch_1)
      @invoice_1 = create(:invoice, customer: @cust_1)
      @invoice_2 = create(:invoice, customer: @cust_2)
      @invoice_3 = create(:invoice, customer: @cust_3)
      @invoice_4 = create(:invoice, customer: @cust_4)
      @invoice_5 = create(:invoice, customer: @cust_5)
      @invoice_6 = create(:invoice, customer: @cust_6)
      InvoiceItem.create(item: @item_1, invoice: @invoice_1)
      InvoiceItem.create(item: @item_1, invoice: @invoice_2)
      InvoiceItem.create(item: @item_1, invoice: @invoice_3)
      InvoiceItem.create(item: @item_1, invoice: @invoice_4)
      InvoiceItem.create(item: @item_1, invoice: @invoice_5)
      InvoiceItem.create(item: @item_1, invoice: @invoice_6)
      create(:transaction, invoice: @invoice_1, result: 'success')
      create(:transaction, invoice: @invoice_1, result: 'failed')
      create(:transaction, invoice: @invoice_1, result: 'failed')
      create(:transaction, invoice: @invoice_2, result: 'success')
      create(:transaction, invoice: @invoice_2, result: 'success')
      create(:transaction, invoice: @invoice_3, result: 'success')
      create(:transaction, invoice: @invoice_3, result: 'success')
      create(:transaction, invoice: @invoice_4, result: 'success')
      create(:transaction, invoice: @invoice_4, result: 'success')
      create(:transaction, invoice: @invoice_4, result: 'success')
      create(:transaction, invoice: @invoice_5, result: 'success')
      create(:transaction, invoice: @invoice_5, result: 'success')
      create(:transaction, invoice: @invoice_6, result: 'success')
      create(:transaction, invoice: @invoice_6, result: 'success')
      create(:transaction, invoice: @invoice_6, result: 'success')
      create(:transaction, invoice: @invoice_6, result: 'success')
    end

    it '#favorite_customers' do
      expected = @merch_1.favorite_customers.map do |customer|
        customer.first_name
      end
      expect(expected).to eq([@cust_6.first_name, @cust_4.first_name, @cust_2.first_name, @cust_3.first_name, @cust_5.first_name])
    end

    it '#top_five_items' do
      @merch_1 = create(:merchant)
      @cust_1 = create(:customer)
      @cust_2 = create(:customer)
      @cust_3 = create(:customer)
      @cust_4 = create(:customer)
      @cust_5 = create(:customer)
      @cust_6 = create(:customer)
      @item_1 = create(:item, merchant: @merch_1, unit_price: 100)
      @item_2 = create(:item, merchant: @merch_1, unit_price: 200)
      @item_3 = create(:item, merchant: @merch_1, unit_price: 500)
      @item_4 = create(:item, merchant: @merch_1, unit_price: 600)
      @item_5 = create(:item, merchant: @merch_1, unit_price: 1000)
      @item_6 = create(:item, merchant: @merch_1, unit_price: 2000)
      @item_7 = create(:item, merchant: @merch_1, unit_price: 5000)
      @invoice_1 = create(:invoice, customer: @cust_1)
      @invoice_2 = create(:invoice, customer: @cust_2)
      @invoice_3 = create(:invoice, customer: @cust_3)
      @invoice_4 = create(:invoice, customer: @cust_4)
      @invoice_5 = create(:invoice, customer: @cust_5)
      @invoice_6 = create(:invoice, customer: @cust_6)
      @invoice_7 = create(:invoice, customer: @cust_6)
      @invoice_8 = create(:invoice, customer: @cust_6)
      @invoice_9 = create(:invoice, customer: @cust_6)
      @invoice_10 = create(:invoice, customer: @cust_6)
      @invoice_11 = create(:invoice, customer: @cust_6)
      @invoice_12 = create(:invoice, customer: @cust_6)
      @invoice_13 = create(:invoice, customer: @cust_6)
      @invoice_14 = create(:invoice, customer: @cust_6)
      InvoiceItem.create(item: @item_1, invoice: @invoice_1, quantity: 1, unit_price: @item_1.unit_price)
      InvoiceItem.create(item: @item_1, invoice: @invoice_2, quantity: 2, unit_price: @item_1.unit_price)
      InvoiceItem.create(item: @item_2, invoice: @invoice_4, quantity: 4, unit_price: @item_2.unit_price)
      InvoiceItem.create(item: @item_2, invoice: @invoice_3, quantity: 3, unit_price: @item_2.unit_price)
      InvoiceItem.create(item: @item_3, invoice: @invoice_5, quantity: 5, unit_price: @item_3.unit_price)
      InvoiceItem.create(item: @item_3, invoice: @invoice_6, quantity: 6, unit_price: @item_3.unit_price)
      InvoiceItem.create(item: @item_4, invoice: @invoice_7, quantity: 7, unit_price: @item_4.unit_price)
      InvoiceItem.create(item: @item_4, invoice: @invoice_8, quantity: 8, unit_price: @item_4.unit_price)
      InvoiceItem.create(item: @item_5, invoice: @invoice_9, quantity: 9, unit_price: @item_5.unit_price)
      InvoiceItem.create(item: @item_5, invoice: @invoice_10, quantity: 10, unit_price: @item_5.unit_price)
      InvoiceItem.create(item: @item_6, invoice: @invoice_11, quantity: 11, unit_price: @item_6.unit_price)
      InvoiceItem.create(item: @item_6, invoice: @invoice_12, quantity: 12, unit_price: @item_6.unit_price)
      InvoiceItem.create(item: @item_7, invoice: @invoice_13, quantity: 13, unit_price: @item_7.unit_price)
      InvoiceItem.create(item: @item_7, invoice: @invoice_14, quantity: 14, unit_price: @item_7.unit_price)
      create(:transaction, invoice: @invoice_1, result: 'success')
      create(:transaction, invoice: @invoice_1, result: 'success')
      create(:transaction, invoice: @invoice_1, result: 'success')
      create(:transaction, invoice: @invoice_2, result: 'success')
      create(:transaction, invoice: @invoice_2, result: 'success')
      create(:transaction, invoice: @invoice_3, result: 'success')
      create(:transaction, invoice: @invoice_3, result: 'success')
      create(:transaction, invoice: @invoice_4, result: 'success')
      create(:transaction, invoice: @invoice_4, result: 'success')
      create(:transaction, invoice: @invoice_4, result: 'success')
      create(:transaction, invoice: @invoice_5, result: 'success')
      create(:transaction, invoice: @invoice_5, result: 'success')
      create(:transaction, invoice: @invoice_6, result: 'success')
      create(:transaction, invoice: @invoice_7, result: 'success')
      create(:transaction, invoice: @invoice_8, result: 'success')
      create(:transaction, invoice: @invoice_9, result: 'success')
      create(:transaction, invoice: @invoice_10, result: 'success')
      create(:transaction, invoice: @invoice_11, result: 'success')
      create(:transaction, invoice: @invoice_12, result: 'success')
      create(:transaction, invoice: @invoice_13, result: 'success')
      create(:transaction, invoice: @invoice_14, result: 'success')
      expected = [@item_7, @item_6, @item_5, @item_4, @item_3]
      
      expect(@merch_1.top_five_items).to eq(expected)
    end
  end
end
