def load_test_data

  @merchant1 = Merchant.create!(name: "Carlos Jenkins") 
  @merchant2 = Merchant.create!(name: "Leroy Jenkins") 
  @merchant3 = Merchant.create!(name: "Melissa Jenkins") 
  @merchant4 = Merchant.create!(name: "Jenny Jenkins") 
  @merchant5 = Merchant.create!(name: "Mickey Mantle") 
  @merchant6 = Merchant.create!(name: "Human who sells stuff") 
  @merchant7 = Merchant.create!(name: "Canine who sells things") 

  @bowl = @merchant1.items.create!(name: "bowl", description: "it's a bowl", unit_price: 650) 
  @knife = @merchant1.items.create!(name: "knife", description: "it's a knife", unit_price: 450) 
  @bowl2 = @merchant2.items.create!(name: "bowl", description: "it's a bowl", unit_price: 350) 
  @knife2 = @merchant2.items.create!(name: "knife", description: "it's a knife", unit_price: 70) 
  @bowl4 = @merchant3.items.create!(name: "bowl", description: "it's a bowl", unit_price: 350) 
  @knife3 = @merchant3.items.create!(name: "knife", description: "it's a knife", unit_price: 20) 
  @bowl5 = @merchant4.items.create!(name: "bowl", description: "it's a bowl", unit_price: 350) 
  @knife4 = @merchant4.items.create!(name: "knife", description: "it's a knife", unit_price: 250) 
  @bowl6 = @merchant5.items.create!(name: "bowl", description: "it's a bowl", unit_price: 350) 
  @knife5 = @merchant5.items.create!(name: "knife", description: "it's a knife", unit_price: 250) 
  @bowl7 = @merchant6.items.create!(name: "bowl", description: "it's a bowl", unit_price: 50) 
  @knife6 = @merchant6.items.create!(name: "knife", description: "it's a knife", unit_price: 250) 
  @bowl8 = @merchant7.items.create!(name: "bowl", description: "it's a bowl", unit_price: 1350) 
  @knife7 = @merchant7.items.create!(name: "knife", description: "it's a knife", unit_price: 550) 


  @cust1 = Customer.create!(first_name: "Laura", last_name: "Fiel")
  @inv1 = @cust1.invoices.create!(status: 1)
  InvoiceItem.create!(item_id: @bowl.id, invoice_id: @inv1.id, status: 2, quantity: 10 , unit_price: 2222)
  InvoiceItem.create!(item_id: @knife4.id, invoice_id: @inv1.id, status: 2, quantity: 6, unit_price: 2050)
  @trans1 = @inv1.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans1_5 = @inv1.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans21 = @inv1.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @inv9 = @cust1.invoices.create!(status: 0)
  InvoiceItem.create!(item_id: @bowl8.id, invoice_id: @inv9.id, status: 2, quantity: 4, unit_price: 8765)


  @cust2 = Customer.create!(first_name: "Bob", last_name: "Fiel")
  @inv2 = @cust2.invoices.create!(status: 1)
  @trans2 = @inv2.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans3 = @inv2.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans20 = @inv2.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 1)
  @inv10 = @cust2.invoices.create!(status: 1)
  @trans18 = @inv10.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 1)

  @cust3 = Customer.create!(first_name: "John", last_name: "Fiel")
  @inv3 = @cust3.invoices.create!(status: 1)
  @inv11 = @cust3.invoices.create!(status: 1)

  @cust4 = Customer.create!(first_name: "Tim", last_name: "Fiel")

  @cust5 = Customer.create!(first_name: "Linda", last_name: "Fiel")

  @cust6 = Customer.create!(first_name: "Lucy", last_name: "Fiel")
  
  @inv4 = @cust4.invoices.create!(status: 1)
  @inv5 = @cust6.invoices.create!(status: 1)
  @inv6 = @cust5.invoices.create!(status: 0)
  @inv7 = @cust4.invoices.create!(status: 0)
  @inv8 = @cust6.invoices.create!(status: 0)
  @inv12 = @cust4.invoices.create!(status: 1)
  InvoiceItem.create!(item_id: @bowl2.id, invoice_id: @inv2.id, status: 2, quantity: 1, unit_price: 6654)
  InvoiceItem.create!(item_id: @bowl4.id, invoice_id: @inv3.id, status: 2, quantity: 4, unit_price: 8765)
  InvoiceItem.create!(item_id: @bowl4.id, invoice_id: @inv4.id, status: 2, quantity: 10 , unit_price: 2222)
  InvoiceItem.create!(item_id: @bowl5.id, invoice_id: @inv5.id, status: 2, quantity: 1, unit_price: 6654)
  InvoiceItem.create!(item_id: @bowl6.id, invoice_id: @inv6.id, status: 2, quantity: 4, unit_price: 8765)
  InvoiceItem.create!(item_id: @bowl7.id, invoice_id: @inv7.id, status: 2, quantity: 10 , unit_price: 2222)
  InvoiceItem.create!(item_id: @bowl8.id, invoice_id: @inv8.id, status: 2, quantity: 1, unit_price: 6654)
  InvoiceItem.create!(item_id: @knife.id, invoice_id: @inv10.id, status: 2, quantity: 2, unit_price: 4567)
  InvoiceItem.create!(item_id: @knife2.id, invoice_id: @inv11.id, status: 2, quantity: 6, unit_price: 2050)
  InvoiceItem.create!(item_id: @knife3.id, invoice_id: @inv12.id, status: 2, quantity: 2, unit_price: 4567)
  InvoiceItem.create!(item_id: @knife5.id, invoice_id: @inv2.id, status: 2, quantity: 2, unit_price: 4567)
  InvoiceItem.create!(item_id: @knife6.id, invoice_id: @inv3.id, status: 2, quantity: 6, unit_price: 2050)
  InvoiceItem.create!(item_id: @knife7.id, invoice_id: @inv4.id, status: 2, quantity: 2, unit_price: 4567)
  InvoiceItem.create!(item_id: @knife5.id, invoice_id: @inv6.id, status: 2, quantity: 6, unit_price: 2050)
  
  @trans4 = @inv3.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans5 = @inv3.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans6 = @inv3.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans7 = @inv4.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans8 = @inv4.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans9 = @inv4.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans10 = @inv4.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans11 = @inv5.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans12 = @inv5.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans13 = @inv5.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans14 = @inv6.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans15 = @inv7.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans16 = @inv8.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans17 = @inv9.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 1)
  @trans19 = @inv11.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 1)
  @trans22 = @inv12.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans23 = @inv1.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans24 = @inv2.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  @trans25 = @inv3.transactions.create!(credit_card_number: 5555555555555555, credit_card_expiration_date: nil, result: 0)
  
end