# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
@merchant = Merchant.create!(name: 'Willms and Sons')
@item1 = @merchant.items.create!(name: "Item 1", description: "First item", unit_price: 1300)
@item2 = @merchant.items.create!(name: "Item 2", description: "Second item", unit_price: 1200)
@customer1 = Customer.create!(first_name: "Annie", last_name: "Anderson")
@customer2 = Customer.create!(first_name: "Bill", last_name: "Bowers")
@customer3 = Customer.create!(first_name: "Chris", last_name: "Carter")
@customer4 = Customer.create!(first_name: "Debra", last_name: "Donald")
@customer5 = Customer.create!(first_name: "Eric", last_name: "Eiden")
@customer6 = Customer.create!(first_name: "Frank", last_name: "Farley")
@customer7 = Customer.create!(first_name: "Greg", last_name: "Gaines")
@customer8 = Customer.create!(first_name: "Hank", last_name: "Harley")
@invoice1 = @customer1.invoices.create!(status: 1)
@invoice2 = @customer2.invoices.create!(status: 1)
@invoice3 = @customer3.invoices.create!(status: 1)
@invoice4 = @customer4.invoices.create!(status: 1)
@invoice5 = @customer5.invoices.create!(status: 1)
@invoice6 = @customer6.invoices.create!(status: 2)
@invoice7 = @customer7.invoices.create!(status: 2)
@invoice8 = @customer8.invoices.create!(status: 0)
@invoice9 = @customer1.invoices.create!(status: 1)
@invoice10 = @customer2.invoices.create!(status: 1)
@invoice11 = @customer3.invoices.create!(status: 1)
@invoice12 = @customer4.invoices.create!(status: 1)
@invoice13 = @customer5.invoices.create!(status: 1)
@invoice14 = @customer6.invoices.create!(status: 1)
@invoice15 = @customer7.invoices.create!(status: 1)
@invoice16 = @customer8.invoices.create!(status: 1)

@invoice_item1 = InvoiceItem.create!(item_id: @item1.id, invoice_id: @invoice1.id)
@invoice_item2 = InvoiceItem.create!(item_id: @item1.id, invoice_id: @invoice2.id)
@invoice_item3 = InvoiceItem.create!(item_id: @item1.id, invoice_id: @invoice2.id)
@invoice_item4 = InvoiceItem.create!(item_id: @item1.id, invoice_id: @invoice2.id)
@invoice_item5 = InvoiceItem.create!(item_id: @item1.id, invoice_id: @invoice2.id)
@invoice_item6 = InvoiceItem.create!(item_id: @item1.id, invoice_id: @invoice2.id)
@invoice_item7 = InvoiceItem.create!(item_id: @item1.id, invoice_id: @invoice2.id)
@invoice_item8 = InvoiceItem.create!(item_id: @item1.id, invoice_id: @invoice2.id)
@invoice_item9 = InvoiceItem.create!(item_id: @item1.id, invoice_id: @invoice2.id)
@invoice_item10 = InvoiceItem.create!(item_id: @item1.id, invoice_id: @invoice2.id)
@invoice_item11 = InvoiceItem.create!(item_id: @item2.id, invoice_id: @invoice2.id)
@invoice_item12 = InvoiceItem.create!(item_id: @item2.id, invoice_id: @invoice2.id)
@invoice_item13 = InvoiceItem.create!(item_id: @item2.id, invoice_id: @invoice2.id)
@invoice_item14 = InvoiceItem.create!(item_id: @item2.id, invoice_id: @invoice2.id)
@invoice_item15 = InvoiceItem.create!(item_id: @item2.id, invoice_id: @invoice2.id)
@invoice_item16 = InvoiceItem.create!(item_id: @item2.id, invoice_id: @invoice2.id)
@invoice_item17 = InvoiceItem.create!(item_id: @item2.id, invoice_id: @invoice2.id)
@invoice_item18 = InvoiceItem.create!(item_id: @item2.id, invoice_id: @invoice2.id)
@invoice_item19 = InvoiceItem.create!(item_id: @item2.id, invoice_id: @invoice2.id)
@invoice_item20 = InvoiceItem.create!(item_id: @item2.id, invoice_id: @invoice2.id)

@transaction1 = Transaction.create!(credit_card_number: 234567, result: 0, invoice_id: @invoice1.id)
@transaction2 = Transaction.create!(credit_card_number: 264567, result: 0, invoice_id: @invoice1.id)
@transaction3 = Transaction.create!(credit_card_number: 234567, result: 0, invoice_id: @invoice1.id)
@transaction4 = Transaction.create!(credit_card_number: 234767, result: 0, invoice_id: @invoice1.id)
@transaction5 = Transaction.create!(credit_card_number: 234537, result: 0, invoice_id: @invoice1.id)
@transaction6 = Transaction.create!(credit_card_number: 454567, result: 0, invoice_id: @invoice1.id)
@transaction7 = Transaction.create!(credit_card_number: 274567, result: 0, invoice_id: @invoice1.id)
@transaction8 = Transaction.create!(credit_card_number: 284567, result: 0, invoice_id: @invoice1.id)
@transaction9 = Transaction.create!(credit_card_number: 234567, result: 0, invoice_id: @invoice1.id)
@transaction10 = Transaction.create!(credit_card_number: 234554, result: 0, invoice_id: @invoice1.id)
@transaction11 = Transaction.create!(credit_card_number: 234856, result: 0, invoice_id: @invoice1.id)
@transaction12 = Transaction.create!(credit_card_number: 234009, result: 0, invoice_id: @invoice1.id)
@transaction13 = Transaction.create!(credit_card_number: 234586, result: 0, invoice_id: @invoice1.id)
@transaction14 = Transaction.create!(credit_card_number: 234524, result: 0, invoice_id: @invoice1.id)
@transaction15 = Transaction.create!(credit_card_number: 234521, result: 0, invoice_id: @invoice1.id)
@transaction16 = Transaction.create!(credit_card_number: 234595, result: 0, invoice_id: @invoice1.id)
@transaction17 = Transaction.create!(credit_card_number: 234511, result: 0, invoice_id: @invoice1.id)
@transaction18 = Transaction.create!(credit_card_number: 234588, result: 0, invoice_id: @invoice1.id)
@transaction19 = Transaction.create!(credit_card_number: 234665, result: 0, invoice_id: @invoice1.id)
@transaction20 = Transaction.create!(credit_card_number: 234326, result: 0, invoice_id: @invoice1.id)